library/urls.py
from django.urls import path

from library import views

app_name = 'library'
urlpatterns = [
    path('', views.home, name='home'),
    path('book/<int:pk>/', views.book_detail, name='book_detail'),
    path('book/<int:book_id>/vote/', views.vote, name='vote'),
    path('authors/', views.authors, name='authors'),
    path('authors/<int:pk>/', views.author_books, name='author_books'),
    path('genres/', views.genres, name='genres'),
    path('forms/', views.forms, name='forms'),
]

libsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from libsite import settings

urlpatterns = [
    path('', include('library.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/models.py
from django.db import models
from sorl.thumbnail import ImageField


class Author(models.Model):
    name = models.CharField('имя', max_length=100)
    description = models.TextField('описание', blank=True)
    photo = ImageField('фото', upload_to='author/%Y/%m/%d/', default='author/default-photo.jpg')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'автор'
        verbose_name_plural = 'авторы'


class Genre(models.Model):
    name = models.CharField('жанр', max_length=20, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'жанр'
        verbose_name_plural = 'жанры'


class Form(models.Model):
    name = models.CharField('форма', max_length=20, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'форма'
        verbose_name_plural = 'формы'


class Book(models.Model):
    name = models.CharField('название', max_length=100)
    description = models.TextField('описание', blank=True)

    pub_date = models.DateField('дата публикации', auto_now_add=True)

    vote_sum = models.IntegerField(default=0)
    vote_count = models.IntegerField(default=0)
    rating = models.DecimalField('рейтинг', max_digits=3, decimal_places=2, default=0.0)

    authors = models.ManyToManyField(Author, verbose_name='авторы')
    genres = models.ManyToManyField(Genre, verbose_name='жанры')
    forms = models.ManyToManyField(Form, verbose_name='формы')

    file = models.FileField('файл книги', upload_to='book/%Y/%m/%d/')
    thumbnail = ImageField('обложка', upload_to='thumbnail/%Y/%m/%d/', default='thumbnail/default-book.jpg')

    def __str__(self):
        return self.name

    def get_authors(self):
        return ', '.join([author.name for author in self.authors.all()])

    get_authors.short_description = 'авторы'

    def get_genres(self):
        return ', '.join([genre.name for genre in self.genres.all()])

    get_genres.short_description = 'жанры'

    def get_forms(self):
        return ', '.join([form.name for form in self.forms.all()])

    get_forms.short_description = 'формы'

    def vote(self, rating):
        self.vote_count += 1
        self.vote_sum += rating

    def save(self, *args, **kwargs):
        self.rating = (self.vote_sum / self.vote_count) if self.vote_count != 0 else 0.0
        super(Book, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'книга'
        verbose_name_plural = 'книги'

library/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from library.models import Author, Book, Form, Genre


def home(request):
    books = Book.objects.order_by('-rating', '-pub_date')
    return render(request, 'library/home.html', {'books': books})


def book_detail(request, pk):
    book = get_object_or_404(Book, pk=pk)
    return render(request, 'library/book_detail.html', {'book': book})


def vote(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    url = request.POST.get('url', reverse('library:home'))

    try:
        rating = int(request.POST['rating'])
        if rating < 1 or rating > 5:
            raise IndexError
    except (KeyError, TypeError, IndexError):
        return HttpResponseRedirect(url)

    book.vote(rating)
    book.save()
    return HttpResponseRedirect(url)


def authors(request):
    author_list = Author.objects.all()
    return render(request, 'library/authors.html', {'authors': author_list})


def author_books(request, pk):
    author = get_object_or_404(Author, pk=pk)
    books = Book.objects.filter(authors__pk=pk)
    return render(request, 'library/author_books.html', {'author': author, 'books': books})


def genres(request):
    genre_list = Genre.objects.all()

    try:
        active_genre = int(request.GET['active-genre'])
        books = Book.objects.filter(genres__id=active_genre)
    except (KeyError, TypeError):
        books = Book.objects.all()

    return render(request, 'library/genres.html', {'genres': genre_list, 'books': books})


def forms(request):
    form_list = Form.objects.all()

    try:
        active_form = int(request.GET['active-form'])
        books = Book.objects.filter(forms__id=active_form)
    except (KeyError, TypeError):
        books = Book.objects.all()

    return render(request, 'library/forms.html', {'forms': form_list, 'books': books})

library/templates/library/author_books.html
{% extends 'library/base.html' %}

{% load thumbnail %}

{% block content %}
    <article class="card author">
        <div class="card__header">
            <h2 class="author__name">{{ author.name }}</h2>
        </div>
        <div class="card__content">
            <div class="card__thumbnail">
                {% thumbnail author.photo '130x190' crop='center' as img %}
                    <img src="{{ img.url }}" alt="thumbnail" class="card__img">
                {% endthumbnail %}
            </div>
            <div class="card__other">
                <p class="card__description">{{ author.description }}</p>
            </div>
        </div>
    </article>
    {% include 'library/list/book.html' with list=books %}
{% endblock %}

library/templates/library/authors.html
{% extends 'library/base.html' %}

{% block content %}
    {% include 'library/list/author.html' with list=authors %}
{% endblock %}

library/templates/library/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Libsite{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'library/style.css' %}">
</head>
<body>

    <header class="header">
        <div class="header__top">
            <a href="{% url 'library:home' %}">
                <img src="{% static 'library/logo_transparent.png' %}" alt="logo" class="logo">
            </a>
            <span class="icon-bars header__bars"></span>
        </div>
        <ul class="menu header__menu header__menu--collapsed">
            <li class="menu__item">
                <a class="menu__link" href="{% url 'library:home' %}">Главная</a>
            </li>
            <li class="menu__item">
                <a class="menu__link" href="{% url 'library:authors' %}">Авторы</a>
            </li>
            <li class="menu__item">
                <a class="menu__link" href="{% url 'library:genres' %}">Жанры</a>
            </li>
            <li class="menu__item">
                <a class="menu__link" href="{% url 'library:forms' %}">Формы</a>
            </li>
        </ul>
    </header>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <footer class="footer">
        © 2019 <a href="{% url 'library:home' %}">«Libsite»</a>
    </footer>

    <script src="{% static 'library/main.js' %}"></script>

</body>
</html>

library/templates/library/book_detail.html
{% extends 'library/base.html' %}

{% load thumbnail %}

{% block content %}
    <article class="card book">
        <div class="card__header">
            <h2 class="book__name">{{ book.name }}</h2>
            <h3 class="book__authors">
                {% for author in item.authors.all %}
                    <a href="{% url 'library:author_books' author.id %}">{{ author.name }}</a>{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </h3>
        </div>
        <div class="card__content">
            <div class="card__thumbnail">
                {% thumbnail book.thumbnail '130x190' crop='center' as img %}
                    <img src="{{ img.url }}" alt="thumbnail" class="card__img">
                {% endthumbnail %}
            </div>
            <div class="card__other">
                <p class="card__description">{{ book.description }}</p>
                {% include 'library/rating.html' %}
                <div class="book__file-wrap">
                    <a class="book__file" href="{{ book.file.url }}">
                        <span class="icon-download"></span> Скачать книгу
                    </a>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

library/templates/library/card/author.html
{% extends 'library/card/card.html' %}

{% block article_class %}author{% endblock %}

{% block header %}
    <h2 class="author__name">
        <a class="link" href="{% url 'library:author_books' item.id %}">{{ item.name }}</a>
    </h2>
{% endblock %}

library/templates/library/card/book.html
{% extends 'library/card/card.html' %}

{% block article_class %}book{% endblock %}

{% block header %}
    <h2 class="book__name"><a class="link" href="{% url 'library:book_detail' item.id %}">{{ item.name }}</a></h2>
    <h3 class="book__authors">{{ item.get_authors }}</h3>
{% endblock %}

{% block other %}
    {% include 'library/rating.html' %}
{% endblock %}

library/templates/library/category_list.html
<div class="category-list">
    {% for item in categories %}
        <div class="category-list__wrap">
            <span class="category-list__item {% if item.id == active_item %}category-list__item--active{% endif %}" data-id="{{ item.id }}">
                {{ item.name }}
            </span>
        </div>
    {% endfor %}
</div>

library/templates/library/forms.html
{% extends 'library/base.html' %}

{% block content %}
    {% include 'library/category_list.html' with categories=forms %}
    <form class="category-list__form" action="{% url 'library:forms' %}" method="get">
        <input class="category-list__active-item" type="hidden" name="active-form">
    </form>

    {% include 'library/list/book.html' with list=books %}
{% endblock %}

library/templates/library/genres.html
{% extends 'library/base.html' %}

{% block content %}
    {% include 'library/category_list.html' with categories=genres %}
    <form class="category-list__form" action="{% url 'library:genres' %}" method="get">
        <input class="category-list__active-item" type="hidden" name="active-genre">
    </form>

    {% include 'library/list/book.html' with list=books %}
{% endblock %}

library/templates/library/home.html
{% extends 'library/base.html' %}

{% block content %}
    {% include 'library/list/book.html' with list=books %}
{% endblock %}

library/templates/library/list/author.html
{% extends 'library/list/list.html' %}

{% block article_class %}author{% endblock %}
{% block link %}{% url 'library:author_books' item.id %}{% endblock %}

{% block header %}
    <h2 class="author__name">
        <a class="link" href="{% url 'library:author_books' item.id %}">{{ item.name }}</a>
    </h2>
{% endblock %}

{% block card_thumbnail %}
    {% with thumb=item.photo %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block other %}
    <p class="card__description">{{ item.description | truncatewords:50 }}</p>
{% endblock %}

library/templates/library/list/book.html
{% extends 'library/list/list.html' %}

{% block article_class %}book{% endblock %}
{% block link %}{% url 'library:book_detail' item.id %}{% endblock %}

{% block header %}
    <h2 class="book__name"><a href="{% url 'library:book_detail' item.id %}">{{ item.name }}</a></h2>
    <h3 class="book__authors">
        {% for author in item.authors.all %}
            <a href="{% url 'library:author_books' author.id %}">{{ author.name }}</a>{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </h3>
{% endblock %}

{% block card_thumbnail %}
    {% with thumb=item.thumbnail %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block other %}
    <p class="card__description">{{ item.description | truncatewords:20 }}</p>
    {% include 'library/rating.html' with book=item %}
{% endblock %}

library/templates/library/list/list.html
{% load thumbnail %}

<div class="list">
    {% for item in list %}
        <div class="list__item">
            <article class="card {% block article_class %}{% endblock %}">
                <div class="card__header">
                    {% block header %}{% endblock %}
                </div>
                <div class="card__content">
                    <div class="card__thumbnail">
                        <a class="link" href="{% block link %}{% endblock %}">
                            {% block card_thumbnail %}
                                {% thumbnail thumb '130x190' crop='center' as img %}
                                    <img src="{{ img.url }}" alt="thumbnail" class="card__img">
                                {% endthumbnail %}
                            {% endblock %}
                        </a>
                    </div>
                    <div class="card__other">
                        {% block other %}
                            <p class="card__description">{{ item.description | truncatewords:20 }}</p>
                        {% endblock %}
                    </div>
                </div>
            </article>
        </div>
    {% empty %}
        <span class="list__empty">Книг не найдено.</span>
    {% endfor %}
</div>

library/templates/library/rating.html
<div class="rating">
    <span>Рейтинг: {{ book.rating | floatformat:'1' }}</span>
    <form action="{% url 'library:vote' book.id %}" method="post">
        {% csrf_token %}

        <!--
        <div class="stars">
            <span class="icon-star stars__out">
                <span class="icon-star rating__in" style="width: 100%;"></span>
            </span>
            <span class="icon-star stars__out">
                <span class="icon-star rating__in" style="width: 100%;"></span>
            </span>
            <span class="icon-star stars__out">
                <span class="icon-star rating__in" style="width: 100%;"></span>
            </span>
            <span class="icon-star stars__out">
                <span class="icon-star rating__in" style="width: 100%;"></span>
            </span>
            <span class="icon-star stars__out">
                <span class="icon-star rating__in" style="width: 33.33%;"></span>
            </span>
        </div>
        -->

        <select name="rating">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5" selected>5</option>
        </select>

        <input type="hidden" name="url" value="{{ request.path }}">

        <input type="submit" value="Оценить" class="rating-submit">
    </form>
</div>